spring.application.name=demo

#DATABSE-CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/revhive_db
spring.datasource.username=sourav
spring.datasource.password=sourav@123

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

