name: Revhive_Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Spring Boot App
        run: mvn clean install

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: revhive-backend
          path: target/*.jar
